# Dependencies
markdown:         redcarpet
highlighter:      pygments
baseurl: /dailyweight

# Permalinks
permalink:        pretty

# Setup
title:            Daily Weight
tagline:          "What get's measured get's managed."
description:      'A simple app to help you achieve your goal weight.'
url:              http://oblakeerickson.github.io/dailyweight/

author:
  name:           'Blake Erickson'
  url:            https://twitter.com/oblakeerickson

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/oblakeerickson/dailyweight
